name: common

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - common

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=defaultdb
      - MYSQL_USER=rockyhub
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - common

volumes:
  redis_data:
  mysql_data:
networks:
  common:
    name: common
    driver: bridge
    external: true