name: common

services:
  redis:
    image: redis:latest
    container_name: common-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - common

  mysql:
    image: mysql:latest
    container_name: common-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=defaultdb
      - MYSQL_USER=rockyhub
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - common

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 5000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=localhost
      - PMA_PASSWORD=password
    networks:
      - common

volumes:
  redis_data:
  mysql_data:

networks:
  common:
    name: common
    driver: bridge
    external: true
