name: common

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - common

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=defaultdb
      - MYSQL_USER=rockyhub
      - MYSQL_PASSWORD=password
    volumes:
      - ./mysql/master.cnf:/etc/mysql/conf.d/master.cnf
      - mysql_data:/var/lib/mysql
    networks:
      - common

  mysql-slave:
    image: mysql:latest
    container_name: mysql-slave
    restart: always
    ports:
      - 3308:3306
    depends_on:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=defaultdb
      - MYSQL_USER=rockyhub
      - MYSQL_PASSWORD=password
    volumes:
      - ./mysql/slave.cnf:/etc/mysql/conf.d/slave.cnf
      - mysql_slave_data:/var/lib/mysql
    networks:
      - common

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - common

volumes:
  redis_data:
  mysql_data:
  mysql_slave_data:


networks:
  common:
    name: common
    driver: bridge
    external: true
